apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "devsecops-app.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "devsecops-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "devsecops-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "devsecops-app.selectorLabels" . | nindent 8 }}
        {{- include "devsecops-app.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "devsecops-app.fullname" . }}-sa
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      securityContext:
        runAsNonRoot: {{ .Values.securityContext.runAsNonRoot }}
        runAsUser: {{ .Values.securityContext.runAsUser }}
        runAsGroup: {{ .Values.securityContext.runAsGroup }}
        seccompProfile:
          {{- toYaml .Values.securityContext.seccompProfile | nindent 10 }}
      containers:
        - name: devsecops-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.app.port }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "devsecops-app.fullname" . }}-config
            - secretRef:
                name: {{ include "devsecops-app.fullname" . }}-secret
          securityContext:
            allowPrivilegeEscalation: {{ .Values.securityContext.allowPrivilegeEscalation }}
            capabilities:
              {{- toYaml .Values.securityContext.capabilities | nindent 14 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: {{ .Values.probes.liveness.path }}
              port: {{ .Values.app.port }}
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.liveness.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.liveness.failureThreshold }}
          readinessProbe:
            httpGet:
              path: {{ .Values.probes.readiness.path }}
              port: {{ .Values.app.port }}
            initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.readiness.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.readiness.failureThreshold }}
