apiVersion: v1
kind: Secret
metadata:
  name: {{ include "devsecops-app.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "devsecops-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  APP_SECRET: {{ .Values.secret.appSecret | quote }}
