apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "devsecops-app.fullname" . }}-sa
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "devsecops-app.labels" . | nindent 4 }}
automountServiceAccountToken: false
