apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: "devsecops-flask-app"
        metrics_path: /metrics
        static_configs:
          - targets:
              - "devsecops-app-helm-devsecops-helm.devsecops-helm.svc.cluster.local:5000"
