apiVersion: v1
kind: ConfigMap
metadata:
  name: devsecops-app-config
  namespace: devsecops-app
  labels:
    app.kubernetes.io/name: devsecops-app
    app.kubernetes.io/part-of: devsecops-pipeline
data:
  APP_NAME: "DevSecOps Flask Application"
  APP_ENV: "kubernetes"
  PORT: "5000"
