apiVersion: v1
kind: Secret
metadata:
  name: devsecops-app-secret
  namespace: devsecops-app
  labels:
    app.kubernetes.io/name: devsecops-app
    app.kubernetes.io/part-of: devsecops-pipeline
type: Opaque
stringData:
  APP_SECRET: "devsecops-local-placeholder"
